version: '2'
services:
  influxdb:
    image: influxdb:2
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=pinger
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
  pinger:
    build: .
    volumes:
      - ./pinger:/app
    command: python /app/pinger.py
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
volumes:
  influxdb-storage:
  grafana-storage: